lines = [
    "# ui/components.py",
    "import base64, os",
    "import streamlit as st",
    "import pandas as pd",
    "",
    "def esc(text):",
    "    return (str(text).replace('&','&amp;').replace('<','&lt;')",
    "            .replace('>','&gt;').replace('\"','&quot;'))",
    "",
    "def safe_write(fn, *args, **kwargs):",
    "    try:",
    "        fn(*args, **kwargs)",
    "        return True",
    "    except Exception as e:",
    "        st.error(f'Write failed: {e}')",
    "        return False",
    "",
    "def toast(message, icon='OK'):",
    "    st.success(f'{icon}  {message}')",
    "",
    "def get_logo_b64():",
    "    for path in ['assets/logo.jpg','assets/logo.png']:",
    "        if os.path.exists(path):",
    "            try:",
    "                with open(path,'rb') as f:",
    "                    return base64.b64encode(f.read()).decode()",
    "            except Exception:",
    "                pass",
    "    return ''",
    "",
    "def compute_status(df):",
    "    df = df.copy()",
    "    for col in ['current_stock','critical_stock','min_stock']:",
    "        df[col] = pd.to_numeric(df.get(col, 0), errors='coerce').fillna(0)",
    "    def _s(row):",
    "        if row['current_stock'] <= row['critical_stock']: return '🔴 Critical'",
    "        if row['current_stock'] <= row['min_stock']:      return '🟡 Low'",
    "        return '🟢 OK'",
    "    df['status'] = df.apply(_s, axis=1)",
    "    return df",
    "",
    "def empty(title, subtitle=''):",
    "    sub = f'<p style=\"font-size:.85rem;\">{esc(subtitle)}</p>' if subtitle else ''",
    "    st.markdown(",
    "        f'<div style=\"text-align:center;padding:2rem 1rem;color:#9CA3AF;\">'",
    "        f'<p style=\"font-size:2rem;margin:0;\">📭</p>'",
    "        f'<p style=\"font-weight:600;margin:.5rem 0 .2rem;\">{esc(title)}</p>'",
    "        f'{sub}</div>',",
    "        unsafe_allow_html=True)",
    "",
    "def safe_idx(lst, value, default=0):",
    "    try:    return lst.index(value)",
    "    except: return default",
    "",
    "def badge(text, bg='#EBEBEB', color='#444'):",
    "    return (f'<span style=\"background:{bg};color:{color};padding:1px 8px;'",
    "            f'border-radius:20px;font-size:.72rem;font-weight:600;\">{esc(text)}</span>')",
    "",
    "def status_badge(status):",
    "    cfg = {'🔴 Critical':('#FFEBEE','#C62828'),'🟡 Low':('#FFF8E1','#E65100'),'🟢 OK':('#E8F5E9','#2E7D32')}",
    "    bg, fg = cfg.get(status, ('#F5F5F5','#595959'))",
    "    return badge(status, bg, fg)",
    "",
    "def metric_card(col, label, value, accent, border_color):",
    "    col.markdown(",
    "        f'<div style=\"background:#FAFAFA;border:1.5px solid {border_color}22;border-radius:10px;padding:1rem 1.2rem;\">'",
    "        f'<p style=\"font-size:.72rem;font-weight:700;text-transform:uppercase;letter-spacing:1.5px;color:#9CA3AF;margin:0 0 .3rem 0;\">{esc(label)}</p>'",
    "        f'<p style=\"font-size:2rem;font-weight:800;color:{accent};margin:0;\">{value}</p>'",
    "        f'</div>',",
    "        unsafe_allow_html=True)",
    "",
    "def stock_table(df, show_min=False):",
    "    if df.empty:",
    "        empty('No products in this station.')",
    "        return",
    "    for _, row in df.iterrows():",
    "        pname = str(row.get('product_name',''))",
    "        cur   = int(pd.to_numeric(row.get('current_stock',0),errors='coerce') or 0)",
    "        unit  = str(row.get('unit',''))",
    "        mn    = int(pd.to_numeric(row.get('min_stock',0),errors='coerce') or 0)",
    "        crit  = int(pd.to_numeric(row.get('critical_stock',0),errors='coerce') or 0)",
    "        if   cur <= crit: dc = '#E53935'",
    "        elif cur <= mn:   dc = '#F4A300'",
    "        else:             dc = '#2E7D32'",
    "        mh = f'<span style=\"font-size:.72rem;color:#9CA3AF;\">min {mn}</span>' if show_min else ''",
    "        st.markdown(",
    "            f'<div style=\"display:flex;align-items:center;justify-content:space-between;padding:.3rem 0;\">'",
    "            f'<span style=\"font-size:.85rem;\"><span style=\"color:{dc};\">●</span> {esc(pname)}</span>'",
    "            f'<span style=\"font-size:.85rem;font-weight:700;\">{cur} {esc(unit)} {mh}</span>'",
    "            f'</div>',",
    "            unsafe_allow_html=True)",
    "",
    "def station_stock_tabs(df, stations, show_min=False):",
    "    stn_col = df['station'] if 'station' in df.columns else None",
    "    present = [s for s in stations if stn_col is not None and s in stn_col.values]",
    "    if not present:",
    "        stock_table(df, show_min)",
    "        return",
    "    tabs = st.tabs(present)",
    "    for tab, stn in zip(tabs, present):",
    "        with tab:",
    "            stock_table(df[df['station']==stn], show_min)",
]

with open('ui/components.py', 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))
print('components.py written OK')
